language: python
sudo: false
python:
  - 3.4
  - 3.5
  - 3.6
matrix:
  include:
    - python: "3.7"
      sudo: required
      dist: xenial
install:
  - pip install -e .
  - pip install -U codecov coverage pytest pytest-cov
script: pytest --cov
after_success:
  - codecov
